### ISSUE TITLE
[BUG] Unable to fetch annotation that is in the list of available annotations  

### ISSUE THREAD

**Issue by caseypaquola** [netneurolab/neuromaps#104]
### Issue summary

Hi neuromappers,

I would like to download all the available PET annotations, however, I run into an issue when fetching all those in the list of available annotations. Specifically, ('norgaard2020', 'flumazenil', 'MNI152', '1mm') appears to be missing on the OSF. See error message in the detailed issue description and the code that produces the error.

Is there another way to access that annotation? Or should it be skipped?

Thanks for the fantastic toolbox!

Best,
Casey

### Detailed issue description

Downloading data from https://files.osf.io/v1/resources/4mw3a/providers/osfstorage/6196caeb0b0c1e03bf7fdd23 ...
Error while fetching file 6196caeb0b0c1e03bf7fdd23; dataset fetching aborted.Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 3, in <module>
  File "/Users/casey/.envs/env_3.9/lib/python3.9/site-packages/neuromaps/datasets/annotations.py", line 226, in fetch_annotation
    dl_file = _fetch_file(dset['url'], str(fn.parent), verbose=verbose,
  File "/Users/casey/.envs/env_3.9/lib/python3.9/site-packages/nilearn/datasets/utils.py", line 665, in _fetch_file
    resp.raise_for_status()
  File "/Users/casey/.envs/env_3.9/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://files.osf.io/v1/resources/4mw3a/providers/osfstorage/6196caeb0b0c1e03bf7fdd23

### Steps to reproduce issue

```python
>>>from neuromaps import datasets
>>>for annotation in datasets.available_annotations(tags=['PET']):
      print(annotation)
      annotations = datasets.fetch_annotation(source=annotation[0])
```

### Software version

0.0.3

### What operating system were you using when you encountered this issue?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Code of Conduct

- [X] I agree to follow the `neuromaps` Code of Conduct

**Comment by justinehansen** [comment]
Hi Casey, thanks for reaching out. Try updating neuromaps to the most recent version on github (`pip install git+https://github.com/netneurotools/neuromaps`), we had a recent PR #100  that fixed some of these images and haven't released the newest neuromaps onto pypi yet.

Let me know if you still run into issues though.

Best,
Justine
