### ISSUE TITLE
Changing Colours in plotting function

### ISSUE THREAD

**Issue by Ghadiirr** [netneurolab/neuromaps#106]
### Description of issue

Hey Justine! 

Great work on Neuromaps, I did a lot of my own project's analysis using the toolbox, and so far it's great!

one issue I'm facing now is with the plotting script, It might be simple but I couldn't figure out the solution.
Whenever I use the function  plot_surf_template, I get a map with colors from blue to orange, I want to have different coloring, something like the ones you used in your original publication about the toolbox. I understand this should be passed through the following code: 
`plt.cm.register_cmap(
    'caret_blueorange', mcolors.LinearSegmentedColormap.from_list('blend', [
        '#00d2ff', '#009eff', '#006cfe', '#0043fe',
        '#fd4604', '#fe6b01', '#ffd100', '#ffff04'
    ])
)`

But still no matter how much I change the color choices I still get the same, am I looking in the right place? Or should I change the code somewhere else? 

### Code of Conduct

- [X] I agree to follow the `neuromaps` Code of Conduct

**Comment by justinehansen** [comment]
Hi @Ghadiirr, glad you're finding neuromaps useful 🙂 
To make your own colourmap, I would recommend creating a colourmap object (e.g. a `ListedColormap`) and passing this through `plot_surf_template` eg,
```
cmap = matplotlib.colors.ListedColormap(cmap)  # cmap is a n x 3 array of RGB colours
# or cmap = matplotlib.colors.ListedSegmentedColormap.from_list('blend', ['#00d2ff', '#009eff', '#006cfe', '#0043fe', '#fd4604', '#fe6b01', '#ffd100', '#ffff04'])
plot_surf_template(data, template, density, cmap=cmap)
```
That said, note that `plot_surf_template` is just a wrapper for `nilearn.plotting.plot_surf`. There are nicer plotting tools out there, including [surfplot](https://github.com/danjgale/surfplot), which is what we used to plot Figure 2 in the neuromaps paper. We didn't adjust the colourmap itself, we just adjusted the colourbar limits to reproduce the way these brain maps were originally published. Colourbar limit adjustment can also be done using `plot_surf_template` via the `vmin` and `vmax` arguments, eg
```
plot_surf_template(data, template, density, cmap=cmap, vmin=-2, vmax=2)
```
Hope that helps!

Justine
