### ISSUE TITLE
Surface-to-Surface Mapping vtk to cifti

### ISSUE THREAD

**Issue by cindyhfls** [netneurolab/neuromaps#109]
### Description of issue

Is it possible to map surfaces from vtk to cifti using neuromaps? How can we do that?

### Code of Conduct

- [X] I agree to follow the `neuromaps` Code of Conduct

**Comment by justinehansen** [comment]
Unfortunately neuromaps doesn't handle vtk files, sorry 🙁 If your vtk file is an fsaverage or civet surface, you would need to change the file type before using neuromaps to transform the surface to fslr (cifti).
