### ISSUE TITLE
[SUGGESTION] - Adding relevant reference to brain annotations.

### ISSUE THREAD

**Issue by GalKepler** [netneurolab/neuromaps#110]
### Description of issue

Hello everyone,

I have a suggestion regarding brain annotations. It would be helpful if a relevant reference could be included when retrieving an annotation. This will help new users associate the annotation they are using with the "target" annotation.

I understand that the "source" entity currently corresponds to such references, but a quick search on Google Scholar was not enough for me to associate available annotations with their respective papers.

This reference should not be mandatory as not all of these annotations are published in scientific papers. Also, it may be useful to attach a corresponding "description" of an annotation - a table describing different components of it, as is often available for annotations.

Please let me know your thoughts. I would be happy to contribute to this effort if you think it's appropriate.

### Code of Conduct

- [X] I agree to follow the `neuromaps` Code of Conduct

**Comment by justinehansen** [comment]
Hi Gal,

Thanks for letting us know, I completely agree. We have a few things in the pipeline which I'll detail here - very happy to hear your thoughts about these and what we could do better.
1. We currently have a table which can be found at our [wiki](https://github.com/netneurolab/neuromaps/wiki) that lists all the annotations, their descriptions, references, etc. We point to this table in the readme and in the citations page of the docs (this was a recent PR #108, prompted by PR #107 ), but maybe we should highlight it elsewhere too to make it easier to find?)
2. We have a PR #73 (work in progress by the amazing @liuzhenqi77) that adds a function `get_annotations_desc` which makes it possible to fetch the annotation information right in Python. You're very welcome to contribute to the PR! (Or add comments and suggestions, whichever you prefer.)

Let me know what you think!

Justine

**Comment by GalKepler** [comment]
Hi Justine,
Thanks for the quick reply.

Both of your answers sound great!

I think my suggestions are:
1. To have `fetch_annotation` return, by default, a simple description of the annotation (which will only include the 2 mandatory elements of an annotation: `"index"` and `"name"` (referring to the discrete labels of the annotation and their names). And maybe a path to a .bib file including any relevant reference(s) of the annotation.
2. To rename the annotations (and/or atlases) to a [BIDS-appropriate form](https://bids-specification.readthedocs.io/en/stable/05-derivatives/03-imaging.html#segmentations).
3. To include supplementary materials such as descriptions (both in [BIDS-appropriate](https://bids-specification.readthedocs.io/en/stable/05-derivatives/03-imaging.html#segmentations) and full forms, since it may be difficult to standardize features\columns across annotations) and references in the OSF repository to have them available for users.

I've created an [OSF repository](https://osf.io/7cdk8/) to describe these suggestions in terms of how to store the annotations.

Let me know if these suggestions are something you think will be useful for the community. I would be more than happy to contribute to these goals (:

Gal.

**Comment by liuzhenqi77** [comment]
Update: Our recently merged PR #73 added the following:
- A function for describing the annotations (in plain text, pandas DataFrame, or LaTex). 
- Fetching the annotations will now also, by default, print out the references. 
- A bib file was included with the package. 
- The documentation page was updated with a full list of descriptions and references for the annotations.
