### ISSUE TITLE
availability of the raw files

### ISSUE THREAD

**Issue by cindyhfls** [netneurolab/neuromaps#114]
### Description of issue

Hi, I was wondering if after the transformation of spaces, is it possible to download the file after transformation (e.g. fsaverage to fsLR) so that it can be loaded in other programs? As far as I know it produces a GiftiImage Object but I have only tried on one. Alternatively, can these raw maps from literature(https://static-content.springer.com/esm/art%3A10.1038%2Fs41592-022-01625-w/MediaObjects/41592_2022_1625_MOESM1_ESM.pdf) be made available and I can transform them with other programs.

### Code of Conduct

- [X] I agree to follow the `neuromaps` Code of Conduct

**Comment by VinceBaz** [comment]
Hi @cindyhfls,

Yes, it is possible to download the files after a transformation. The image files are loaded in Python as either GiftiImage objects (for surface data) or Nifti1Image (for volumetric data). Transformed images will either be GiftiImages or Nifti1Images as well. These object classes are originally from [NiBabel](https://nipy.org/nibabel/), a Python toolbox to access common neuroimaging file formats. To save the transformed images that you generate with neuromaps, you can use the `save` function from Nibabel:

```
import nibabel as nib
nib.save(img, data_path)
```

Regarding you alternative question: when you fetch a brain map using the `datasets.fetch_annotation` function or an atlas using the `datasets.fetch_atlas` function, the brain maps (or atlases) are, by default, downloaded to a sub-directory of `$HOME/neuromaps-data` on your local computer. From there you can use them however you want, and transform/use them in other programs.

I hope this helps! Let me know if you have any other question :smile:

**Comment by cindyhfls** [comment]
Yes I tried that but it cannot be opened, is it possible to obtain the raw numerical data in a gifti/cifti format?

**Comment by VinceBaz** [comment]
Hi again, 

Could you show me an example of what you tried to do? Using `nib.save` is the usual method to save the transformed image files that you obtain with neuromaps (which is what you want, if I understand correctly?). 

You should be able to open these files with any other program that can read gifti or nifti files. I you cannot do that, I'd need more information to be able to help you out 😄

**Comment by cindyhfls** [comment]
No I don't want the image, I want the raw values in a gifti or cifti file if that makes sense? The saved file is a GIFTIImage which I could not open.

**Comment by cindyhfls** [comment]
Oh actually I could save it as .func.gii and it works. Sorry for the confusion.
