### ISSUE TITLE
FutureWarning "Importing from 'nilearn.input_data'"

### ISSUE THREAD

**Issue by LeonDLotter** [netneurolab/neuromaps#116]
### Description of issue

Hi y'all,
On import of `neurmaps.parcellate.Parcellater` with current nilearn versions, nilearn returns: 
```
FutureWarning: The import path 'nilearn.input_data' is deprecated in version 0.9. Importing from 'nilearn.input_data' will be possible at least until release 0.13.0. Please import from 'nilearn.maskers' instead.
```
Fix:
Replace, e.g., [neuromaps.parcellate line 7](https://github.com/netneurolab/neuromaps/blob/abc085acdc96223a4848b331951afd4aab529a20/neuromaps/parcellate.py#L7C1-L7C1): `from nilearn.input_data import NiftiLabelsMasker` 
with: `from nilearn.maskers import NiftiLabelsMasker` 

Best,
Leon

### Code of Conduct

- [X] I agree to follow the `neuromaps` Code of Conduct

**Comment by VinceBaz** [comment]
Hi @LeonDLotter,
I just fixed this. Thanks a lot for pointing this out :smile:
