### ISSUE TITLE
Curious behaviour loading an MNI152 volume and trying to parcellate

### ISSUE THREAD

**Issue by ltuominen** [netneurolab/neuromaps#122]
### Description of issue

I am reporting curious behaviour. Not sure if this is bug or if I am just doing something silly.

I have this file in MNI152, 2mm: 'Neglect_network_map.nii'

I say:
```
neglect = load_data(home + '/data/Neglect_network_map.nii')
print(type(neglect), neglect.shape)
```
 <class 'numpy.ndarray'> (91, 109, 91)

Then I say: 
```
schaefer_vol = fetch_atlas_schaefer_2018(n_rois=200, yeo_networks=7, resolution_mm=2)  
parcellation_mni = schaefer_vol['maps']
parcellater_mni = Parcellater(schaefer_vol['maps'], 'mni152')
parcellater_mni.fit_transform(neglect, space='mni152')
```
I get this error:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[51], line 4
      2 parcellation_mni = schaefer_vol['maps']
      3 parcellater_mni = Parcellater(schaefer_vol['maps'], 'mni152')
----> 4 parcellater_mni.fit_transform(neglect, space='mni152')

File ~/anaconda3/lib/python3.10/site-packages/neuromaps/parcellate.py:224, in Parcellater.fit_transform(self, data, space, ignore_background_data, background_value, hemi)
    220 def fit_transform(self, data, space, ignore_background_data=False,
    221                   background_value=None, hemi=None):
    222     """ Prepare and perform parcellation of `data`
    223     """
--> 224     return self.fit().transform(data, space, ignore_background_data,
    225                                 background_value, hemi)

File ~/anaconda3/lib/python3.10/site-packages/neuromaps/parcellate.py:150, in Parcellater.transform(self, data, space, ignore_background_data, background_value, hemi)
    145     raise ValueError('Cannot parcellate data from {hemi} hemisphere '
    146                      'when parcellation was provided for incompatible '
    147                      'hemisphere: {self.hemi}')
    149 if isinstance(data, np.ndarray):
--> 150     data = _array_to_gifti(data)
    151 if self.resampling_target in ('data', None):
    152     resampling_method = 'nearest'

File ~/anaconda3/lib/python3.10/site-packages/neuromaps/parcellate.py:28, in _array_to_gifti(data)
     25 def _array_to_gifti(data):
     26     """ Converts numpy `array` to tuple of gifti images
     27     """
---> 28     return tuple(construct_shape_gii(arr) for arr in np.split(data, 2))

File <__array_function__ internals>:200, in split(*args, **kwargs)

File ~/anaconda3/lib/python3.10/site-packages/numpy/lib/shape_base.py:872, in split(ary, indices_or_sections, axis)
    870     N = ary.shape[axis]
    871     if N % sections:
--> 872         raise ValueError(
    873             'array split does not result in an equal division') from None
    874 return array_split(ary, indices_or_sections, axis)

ValueError: array split does not result in an equal division

However, things work just fine when I say this instead:
```
neglect = transforms.mni152_to_mni152(home + '/data/Neglect_network_map.nii', '2mm')
neglect_parc = parcellater_mni.fit_transform(neglect, space='mni152')
```

### Code of Conduct

- [X] I agree to follow the `neuromaps` Code of Conduct

**Comment by justinehansen** [comment]
This is neuromaps doing something silly :slightly_smiling_face: 
If you apply the parcellater to your image (`neglect`) as a nifti image instead of as an array, it'll work, eg:

```
from neuromaps.images import load_nifti
neglect_parc = parcellater_mni.fit_transform(load_nifti(neglect), space='mni152')
```

Right now neuromaps is assuming that if the data is an array, it's a surface-based map and it tries to turn it into a (left, right) tuple of Gifti images. This doesn't work for volumetric data because it's not always possible to split the data in half the way it's done for gifti images. Your workaround (using `mni152_to_mni152`) reshapes the data into a shape that can be split in half perfectly but it's better not to do this transformation.
