### ISSUE TITLE
Applying spatially-constrained nulls to one brain map

### ISSUE THREAD

**Issue by Melissa1909** [netneurolab/neuromaps#130]
### Description of issue

Hi guys,
my colleagues work on a meta-analysis of brain aberrations in a brain disorder measured via different modalities and integrated these deviations across studies and across modalities into two (instead of seven) brain maps showing voxel-wise representative deviations across subjects and modalities. 
We want to assess which voxels are significantly different from zero (i.e., the idea of a 1-sample t-test) but considering spatial autocorrelation. Our idea was to use the burt2020 method to generate spatially-constrained null distributions and assess the significance of the "integration" brain maps against a map containing only zeros. Since we have not found any body of literature who has applied spatial nulls in that manner, we would like to know what the developers think about hijacking neuromaps for that application.
Best, Melissa

### Code of Conduct

- [X] I agree to follow the `neuromaps` Code of Conduct

**Comment by Melissa1909** [comment]
Hi, 
can anyone give me feedback on that?
Thank you in advance! 
Best, Melissa

**Comment by justinehansen** [comment]
Hey Melissa, sorry about the delay and thanks for the reminder 🙂 So we've discussed it a bit amongst ourselves and honestly we're not totally sure how to proceed or if using the spatial nulls is the way to go here. (It's also possible we're not fully understanding your proposed method.) As with any new method, it might be worth giving it a shot and taking a look at the null vs empirical to see if it seems reasonable? Sorry we're not being more helpful here 😅

**Comment by Melissa1909** [comment]
Hi Justine,
alright, then we'll just try it! Thank you!
Best, Melissa

**Comment by liuzhenqi77** [comment]
Close due to inactivity. Please feel free to reopen if there are any updates.
