### ISSUE TITLE
Can't import from neuromaps.datasets

### ISSUE THREAD

**Issue by ltuominen** [netneurolab/neuromaps#133]
### Issue summary

I have trouble importing from neuromaps.datasets after reinstalling neuromaps 

### Detailed issue description

Just pip installed the latest neuromaps:
"Successfully installed neuromaps-0.0.4+37.g9a0b149" 

I get the following error:
from neuromaps import parcellate
ImportError: cannot import name 'ALIAS' from 'neuromaps.datasets' (unknown location)

Also: 
from neuromaps.datasets import available_annotations
ImportError: cannot import name 'available_annotations' from 'neuromaps.datasets' (unknown location)

But no problem importing some other modules like:
from neuromaps.stats import compare_images

Cheers
Lauri

### Steps to reproduce issue

```python
>>>from neuromaps import parcellate
>>>
>>>
...
```

### Software version

0.0.4+37.g9a0b149

### What operating system were you using when you encountered this issue?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Code of Conduct

- [X] I agree to follow the `neuromaps` Code of Conduct

**Comment by liuzhenqi77** [comment]
Hi, thanks for reporting the issue! 

This is indeed a bug introduced when we were trying to update the package structure in the past month. We have pushed a fix that hopefully would resolve this problem. Please try again with the new version (remove the old folder, redo git clone from the main branch, and install like before).

Please let us know if there are further issues. Thank you!

Zhen-Qi

**Comment by ltuominen** [comment]
Amazing! Works like a charm

**Comment by liuzhenqi77** [comment]
Awesome to hear! Thanks again for letting us know about this and sorry for the trouble.
