### ISSUE TITLE
colormap available?

### ISSUE THREAD

**Issue by cindyhfls** [netneurolab/neuromaps#144]
### Description of issue

Hi I was wondering if the colormaps (esp. the workbench ones) would be made available in simple files (e.g. .csv, .txt)?

Best,
Cindy

### Code of Conduct

- [X] I agree to follow the `neuromaps` Code of Conduct

**Comment by liuzhenqi77** [comment]
Hi, thanks for the suggestion! 

For colormaps, we usually call matplotlib or other external libraries. For example, it seems some of the connectome workbench colormaps are available in nilearn.
https://nilearn.github.io/stable/auto_examples/01_plotting/plot_colormaps.html

As we are still devoting most of our time improving the core functions (null models, transforms, etc), we might not be able to add a new colormap module to neuromaps in the near future. However, we have a [function](https://netneurolab.github.io/netneurotools/generated/netneurotools.colors.available_cmaps.html) in netneurotools aiming at this direction (with more colormap-related functions expected in that module). The connectome workbench palettes should be available [here](https://github.com/Washington-University/workbench/blob/master/src/Files/PaletteFile.cxx). If you could extract a list of colors compatible with matplotlib, then it should be easy to put it in that module. Please feel free to try implement this and open a pull request there if you feel like it would be useful for you and others!

Thanks a lot!

**Comment by liuzhenqi77** [comment]
Close due to inactivity. Please feel free to reopen if issue persists.
