### ISSUE TITLE
[BUG] Issue with Nilearn compatability

### ISSUE THREAD

**Issue by MIZwally** [netneurolab/neuromaps#149]
### Issue summary

I am receiving an error indicating that some nilearn functions cannot be imported.

### Detailed issue description

Specifically for `_fetch_files()`, I believe Nilearn has changed their repo structure in newer updates. The import `from nilearn.datasets.utils import _fetch_files` is now 'from nilearn.datasets._utils import fetch_files'. Specifying a version of nilearn in your requirements.txt file or updating the calls should fix the issue.

### Steps to reproduce issue

```python
>>> from neuromaps import datasets, images, nulls, resampling
```

### Software version

3.11.7 (main, Dec 15 2023, 18:12:31) [GCC 11.2.0]
0.0.4

### Code of Conduct

- [X] I agree to follow the `neuromaps` Code of Conduct

**Comment by VinceBaz** [comment]
Hi @MIZwally. This issue was fixed in our most recent release of neuromaps ([0.05](https://github.com/netneurolab/neuromaps/releases/tag/0.0.5)) :smile:

**Comment by liuzhenqi77** [comment]
Close due to inactivity. Please feel free to reopen if issue persists.

**Comment by LuuuXG** [comment]
> Hi @MIZwally. This issue was fixed in our most recent release of neuromaps ([0.0.5](https://github.com/netneurolab/neuromaps/releases/tag/0.0.5)) 😄

Hello Neuromaps development team. I met this issue with Neuromaps 0.0.5 and Nilearn 0.10.4 when referring the 'Parcellations' part in the user guide.
```python
from netneurotools import datasets as nntdata

Traceback (most recent call last):
  File "E:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-14b6b8744890>", line 1, in <module>
    from netneurotools import datasets as nntdata
  File "D:\Program Files\JetBrains\PyCharm 2023.1.4\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "E:\Anaconda3\lib\site-packages\netneurotools\datasets\__init__.py", line 12, in <module>
    from .fetchers import (fetch_cammoun2012, fetch_pauli2018, fetch_fsaverage,
  File "D:\Program Files\JetBrains\PyCharm 2023.1.4\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "E:\Anaconda3\lib\site-packages\netneurotools\datasets\fetchers.py", line 12, in <module>
    from nilearn.datasets.utils import _fetch_files
ImportError: cannot import name '_fetch_files' from 'nilearn.datasets.utils' (E:\Anaconda3\lib\site-packages\nilearn\datasets\utils.py)
```
It was resolved after updating 'netneurotools'.

btw, in the documentation, the last line seems to be `fc_grad_parc = parc.fit_transform(fc_grad, 'fsLR')` rather than `fc_grad_parc = parc.fit_transform(fcgradient, 'fsLR')`.

![image](https://github.com/netneurolab/neuromaps/assets/104219102/55414293-89ed-4739-8b1a-c6aad7a3c396)
