### ISSUE TITLE
 hierarchy of network maps

### ISSUE THREAD

**Issue by cindyhfls** [netneurolab/neuromaps#155]
### Brain map source

- [ ] I am sharing a brain map from my own research
- [X] I am requesting a brain map be added from a published article

### Licensing

- [X] I have the necessary permissions to share these brain map(s) under a CC-BY license or they have already been made openly-available under a similar license.

### Map description

Hi,

I was wondering if you can find the hierarchy of network maps found here. I would like to have it in an fsLR 32k space. 

![image](https://github.com/netneurolab/neuromaps/assets/30844460/77d236e1-bb4b-4b19-8f1e-324d6c0a3c69)

https://pubmed.ncbi.nlm.nih.gov/37609246/

Best,
Cindy

### Reference DOI

https://pubmed.ncbi.nlm.nih.gov/37609246/

### Code of Conduct

- [X] I agree to follow the `neuromaps` Code of Conduct

**Comment by justinehansen** [comment]
Hey Cindy, thanks for letting us know. Neuromaps actually has a contribution pipeline sooo it would be great if you added it to neuromaps if it's open access :grin:
