### ISSUE TITLE
Question about transforming to sphere space

### ISSUE THREAD

**Issue by Aceticia** [netneurolab/neuromaps#156]
### Description of issue

Hi, thanks for the fabulous package. I have some data in MNI space and I'm interested in resampling them to the fsaverage space but represented on the sphere. I assume the normal `mni_to_fsaverage` transforms to the pial?

### Code of Conduct

- [X] I agree to follow the `neuromaps` Code of Conduct

**Comment by justinehansen** [comment]
`mni_to_fsaverage` is transforming a 3D volumetric image to a 1D vector of length $n$, where $n$ is the number of vertices in `fsaverage` space. You can use plotting software such as the connectome workbench to plot the output on many different surface e.g. sphere, pial, midthickness, grey/white matter boundary. You'll just need the spherical (or pial, or midthickness, etc) `fsaverage` surface to do the plotting, which you can fetch from `neuromaps.atlas.fetch_fsaverage()`.

So in your case what I'd do is:
1. use `mni_to_fsaverage` to transform your volume to the surface, and save the output (two giftis) somewhere
2. run `fetch_fsaverage()` which will download all the `fsaverage` surface files
3. use connectome workbench to plot on the sphere by loading in the LH and RH sphere files (which you downloaded in step 2) as well as your output giftis from step 1 to visualize data on the sphere

I hope that helps!

Justine
