### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by juansanchezpena** [netneurolab/neuromaps#160]
### Description of issue

Is there any documentation on the input args for the container version ?
We are trying to add neuromaps as an option in our VM's through AWS using a GPU. 
Thanks so much

### Code of Conduct

- [X] I agree to follow the `neuromaps` Code of Conduct

**Comment by liuzhenqi77** [comment]
Hi,

Our docker image is simply a Python base layer installed with some necessary dependencies and neuromaps itself, as you can see from the Dockerfile [here](https://github.com/netneurolab/neuromaps/blob/main/Dockerfile). The input commands for docker should be the same as how you would call Python scripts normally.

Thanks!
