### ISSUE TITLE
matplotlib version

### ISSUE THREAD

**Issue by enicolaisen** [netneurolab/neuromaps#163]
### Description of issue

Hi!

I think that the toolkit does not work with the some versions of matplotlib (for instance, 3.9.0), but it does with version 3.5.1. So, maybe it is worth mentioning in the requirements.

More details:

When using version 3.9.0 and I tried to do:
`from neuromaps import plotting`, 

I got: 
`the error module 'matplotlib.cm' has no attribute 'register_cmap' `

It seems that the problematic line was from file `neuromaps/plotting.py:16`: 
````
16 'plt.cm.register_cmap(     
17 'caret_blueorange', mcolors.LinearSegmentedColormap.from_list('blend', [ 
18         '#00d2ff', '#009eff', '#006cfe', '#0043fe', 
19         '#fd4604', '#fe6b01', '#ffd100', '#ffff04' 
20     ])

````

This was solved when using version 3.5.1

Best,
Eliana

### Code of Conduct

- [X] I agree to follow the `neuromaps` Code of Conduct

**Comment by eric2302** [comment]
Hi Eliana,

Thanks for letting us know. I committed a fix for this. Can you please pip install neuromaps with the new changes and tell me if there's no more error message? 

The installation can be done in the terminal with
`pip install git+https://github.com/netneurolab/neuromaps.git@0b8abd01e4799db64caf652bce1cea47b5d38ec6`

Best,
Eric

**Comment by liuzhenqi77** [comment]
Close with #164. Please feel free to reopen if issue persists.
