### ISSUE TITLE
knn specification for burt 2020 (volumes)

### ISSUE THREAD

**Issue by tincala91** [netneurolab/neuromaps#170]
### Description of issue

Hi! 

I have to generate some nulls for statistical significance using burt2020. 

I noticed that in Markello 2021 Neuroimage, your team recommended to use burt2020 not with default settings but adapting the knn hyperparameter to match the number of vertices in the input data, to avoid having an unnecessary number of false positives.

This is not mentioned in the current documentation - is this adjustment also implemented in neuromaps? 

From a quick look at the code it seems like the default parameters are used instead (but I might be wrong of course :))

Thank you for the clarification

Arianna

### Code of Conduct

- [X] I agree to follow the `neuromaps` Code of Conduct

**Comment by tincala91** [comment]
PS: in my specific case, I am using burt_2020 with a volume file

**Comment by VinceBaz** [comment]
Hi @tincala91,

Sorry for the delay! Yes it is possible to modify the hyperparameters for the `burt2020` function. 

The `burt2020` function relies on classes from brainsmash (`Base` when you have a parcellation and `Sampled` when you don't) and it allows you to pass additional keyword arguments to them to modify their hyperparameters.

For instance, when you don't use a parcellation, you can modify the number of nearest regions to keep in the neighborhood of each region by changing the `knn` parameter of the `Sampled` constructor which by default has a value of 1000. 

You can take a look at the brainsmash documentation for the [Base](https://brainsmash.readthedocs.io/en/latest/source/brainsmash.mapgen.html#brainsmash.mapgen.base.Base) and [Sampled](https://brainsmash.readthedocs.io/en/latest/source/brainsmash.mapgen.html#brainsmash.mapgen.sampled.Sampled) classes for a list of all the available hyperparameters.

I hope it clarify things! Let me know if you have additional questions :smile:

Best,
Vince

**Comment by tincala91** [comment]
Thank you!
