### ISSUE TITLE
Add neuromaps to pypi or conda?

### ISSUE THREAD

**Issue by JohannesWiesner** [netneurolab/neuromaps#183]
Are there any plans to create a pypi or conda repository for neuromaps?

**Comment by eric2302** [comment]
Hi Johannes,
There is a neuromaps repository on pypi ([https://pypi.org/project/neuromaps/](https://pypi.org/project/neuromaps/)). Let us know if this is what you were looking for.

Best,
Eric

**Comment by liuzhenqi77** [comment]
Resolved by #181 .
