### ISSUE TITLE
Missing 7 Annotations, specifically: ('galovic2021', 'ge179', 'MNI152', '1mm')

### ISSUE THREAD

**Issue by baharhazal** [netneurolab/neuromaps#184]
Hi,

I've tried several methods for the toolbox using both Docker and the Python library in virtual env (clone githib), but I consistently end up with only **79 annotations**, while the provided Excel sheet lists 86. This discrepancy is also mentioned here: [neuromaps GitHub](https://github.com/netneurolab/neuromaps/blob/main/neuromaps/datasets/data/osf.json). 

However, despite trying various approaches, I haven't been able to fetch the additional data. I am simply using the example function to fetch all annotations:

`annotation = datasets.fetch_annotation(source='all')` or
`annotations = datasets.available_annotations()`

Specifically, I am trying to find ('galovic2021', 'ge179', 'MNI152', '1mm'), but it doesn’t seem to exist.
Can you please help me fetch this and any other missing annotations?
Thanks!

**Comment by justinehansen** [comment]
Hi, is your neuromaps up to date with the version on github? There were several maps, including galovic2021, added in a recent PR #168.

**Comment by baharhazal** [comment]
Thanks for your prompt response. As you suggested, I was using an earlier version, but I have now updated to the latest version and I have access to all 86. Thanks again!
