### ISSUE TITLE
[BUG] Error during fetch_annotation

### ISSUE THREAD

**Issue by tincala91** [netneurolab/neuromaps#185]
### Issue summary

Cannot download any annotation due to path error: `str object has no attribute mkdir`, triggered in nilearn's `fetch_single_file`. 

Apparently in version 0.11.0 of nilearn, they require a Path object for `data_dir`, while in [fetch_annotation.py, l288](https://github.com/netneurolab/neuromaps/blame/3770570d235a50ad115ebfd2f11865a009f727d3/neuromaps/datasets/annotations.py#L288) the data dir is casted to string.

Removing the `str(data_dir)` fixes issue, but it will be incompatible with older nilearn.

### Steps to reproduce issue

```python
pip install -U nilearn=0.11.0

from pathlib import Path
p = Path(r'C:/Users/asala/neuromaps-data')

from neuromaps.datasets import fetch_annotation
from neuromaps.datasets import available_annotations
for annotation in available_annotations(tags='PET'):
    print(annotation)
    fetch_annotation(source=annotation[0], desc=annotation[1],
                     space=annotation[2], den=annotation[3],
                     data_dir=p)
```

### Code of Conduct

- [x] I agree to follow the `neuromaps` Code of Conduct

**Comment by liuzhenqi77** [comment]
Hi, thanks so much for reporting and pinpointing the bug! I've opened a PR for this.

Removing the `str()` works for me for both `0.11.0` and `0.10.X` versions. May I ask which older nilearn version would be incompatible on your end? Thanks!

**Comment by tincala91** [comment]
I checked with nilearn 0.10.4, and it accepts the string object instead of path, and use the usual `os.path` functions.

os.path accepts Path objects since Python3.6, so I feel it is actually safe to remove the cast to string.

**Comment by liuzhenqi77** [comment]
Sorry for the late reply & thanks so much for the feedback! The PR has been merged. Please feel free to reopen & submit issues if anything.
