### ISSUE TITLE
Unable to download corresponding atlas through fetch_anntation()

### ISSUE THREAD

**Issue by masai1998** [netneurolab/neuromaps#187]
### Description of issue

When I use the example code:
`from neuromaps.datasets import fetch_annotation`
`fetch_annotation(source='hcps1200', desc='megalpha', space='fsLR', den='4k')`
I always get a HTTPError of `404 Client Error: Not Found for url`
I have already tried github and pip version of Neuromaps，and I also tried VPN. None of them work.
The detailed error is as follows:
`HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/cos-osf-prod-files-ca-1/637680180b56a67203149d084c1553f785557a9b9ab2f67b1fb8bf01bfb12699?response-content-disposition=attachment%3B%20filename%3D%22source-hcps1200_desc-megalpha_space-fsLR_den-4k_hemi-L_feature.func.gii%22%3B%20filename%2A%3DUTF-8%27%27source-hcps1200_desc-megalpha_space-fsLR_den-4k_hemi-L_feature.func.gii&GoogleAccessId=files-ca-1%40cos-osf-prod.iam.gserviceaccount.com&Expires=1733837814&Signature=r5KB3pCZPowfDBXvSz8kiEyvLt8Lo%2B5P9jWk%2FID9Daay93tN8Y7n4pIy1HYGSAJc3ej21aBkuibEq4LW8uhLFCA32EWC9LVwWSSheq3H3g2BlnMEQPCxIuhNPKLVeljPwGwX%2BU3fqqicI4%2B09e%2FXKNWGZdb94AogoDXsgUBF%2FdmvTnlvP%2Ful%2BORUHj6J%2F4b8%2BhDlAR1Flno52JZJmescE790oTw7hMa%2FHKtmeGTi5extQyWl11SvTyjnZdQZ2MnIftCqGJLWdZFix%2F5BcfVM2SltJ53Zlv3CqYv%2BS4%2B4W4hgWMUMMDMq%2F7haemwcUxyR9d5Gls6BaGH%2FoPJzy%2FWIBg%3D%3D!`
[Image](https://github.com/user-attachments/assets/66630f29-9c19-4866-8c73-b162bd60a86c)

### Code of Conduct

- [x] I agree to follow the `neuromaps` Code of Conduct

**Comment by masai1998** [comment]
Where can I directly download annotation atlas from neuromap.datasets?

**Comment by liuzhenqi77** [comment]
Hi, it's possible but not recommended. Please refer to [this reply](https://github.com/netneurolab/neuromaps/issues/141#issuecomment-1922809176). Thanks.
