### ISSUE TITLE
NMDA receptors not available

### ISSUE THREAD

**Issue by Turius** [netneurolab/neuromaps#188]
### Description of issue

This map "galovic2021-ge179-MNI152-1mm" returns a blank.

How to replicate:
fetch_annotation(source='galovic2021', desc='ge179', space='MNI152', res='1mm')

### Code of Conduct

- [x] I agree to follow the `neuromaps` Code of Conduct

**Comment by liuzhenqi77** [comment]
Hey I cannot reproduce this. Could you please provide more information, like the version you are using & errors?

**Comment by Turius** [comment]
Sure,

available_annotations()

does not list it:
`[('abagen', 'genepc1', 'fsaverage', '10k'),
 ('aghourian2017', 'feobv', 'MNI152', '1mm'),
 ('alarkurtti2015', 'raclopride', 'MNI152', '3mm'),
 ('bedard2019', 'feobv', 'MNI152', '1mm'),
 ('beliveau2017', 'az10419369', 'MNI152', '1mm'),
 ('beliveau2017', 'az10419369', 'fsaverage', '164k'),
 ('beliveau2017', 'cimbi36', 'MNI152', '1mm'),
 ('beliveau2017', 'cimbi36', 'fsaverage', '164k'),
 ('beliveau2017', 'cumi101', 'MNI152', '1mm'),
 ('beliveau2017', 'cumi101', 'fsaverage', '164k'),
 ('beliveau2017', 'dasb', 'MNI152', '1mm'),
 ('beliveau2017', 'dasb', 'fsaverage', '164k'),
 ('beliveau2017', 'sb207145', 'MNI152', '1mm'),
 ('beliveau2017', 'sb207145', 'fsaverage', '164k'),
 ('ding2010', 'mrb', 'MNI152', '1mm'),
 ('dubois2015', 'abp688', 'MNI152', '1mm'),
 ('dukart2018', 'flumazenil', 'MNI152', '3mm'),
 ('dukart2018', 'fpcit', 'MNI152', '3mm'),
 ('fazio2016', 'madam', 'MNI152', '3mm'),
 ('finnema2016', 'ucbj', 'MNI152', '1mm'),
 ('gallezot2010', 'p943', 'MNI152', '1mm'),
 ('gallezot2017', 'gsk189254', 'MNI152', '1mm'),
 ('hcps1200', 'megalpha', 'fsLR', '4k'),
 ('hcps1200', 'megbeta', 'fsLR', '4k'),
 ('hcps1200', 'megdelta', 'fsLR', '4k'),
 ('hcps1200', 'meggamma1', 'fsLR', '4k'),
 ('hcps1200', 'meggamma2', 'fsLR', '4k'),
 ('hcps1200', 'megtheta', 'fsLR', '4k'),
 ('hcps1200', 'megtimescale', 'fsLR', '4k'),
 ('hcps1200', 'myelinmap', 'fsLR', '32k'),
 ('hcps1200', 'thickness', 'fsLR', '32k'),
 ('hesse2017', 'methylreboxetine', 'MNI152', '3mm'),
 ('hill2010', 'devexp', 'fsLR', '164k'),
 ('hill2010', 'evoexp', 'fsLR', '164k'),
 ('hillmer2016', 'flubatine', 'MNI152', '1mm'),
 ('jaworska2020', 'fallypride', 'MNI152', '1mm'),
 ('kaller2017', 'sch23390', 'MNI152', '3mm'),
 ('kantonen2020', 'carfentanil', 'MNI152', '3mm'),
 ('laurikainen2018', 'fmpepd2', 'MNI152', '1mm'),
 ('margulies2016', 'fcgradient01', 'fsLR', '32k'),
 ('margulies2016', 'fcgradient02', 'fsLR', '32k'),
 ('margulies2016', 'fcgradient03', 'fsLR', '32k'),
 ('margulies2016', 'fcgradient04', 'fsLR', '32k'),
 ('margulies2016', 'fcgradient05', 'fsLR', '32k'),
 ('margulies2016', 'fcgradient06', 'fsLR', '32k'),
 ('margulies2016', 'fcgradient07', 'fsLR', '32k'),
 ('margulies2016', 'fcgradient08', 'fsLR', '32k'),
 ('margulies2016', 'fcgradient09', 'fsLR', '32k'),
 ('margulies2016', 'fcgradient10', 'fsLR', '32k'),
 ('mueller2013', 'intersubjvar', 'fsLR', '164k'),
 ('naganawa2020', 'lsn3172176', 'MNI152', '1mm'),
 ('neurosynth', 'cogpc1', 'MNI152', '2mm'),
 ('norgaard2021', 'flumazenil', 'MNI152', '1mm'),
 ('norgaard2021', 'flumazenil', 'fsaverage', '164k'),
 ('normandin2015', 'omar', 'MNI152', '1mm'),
 ('radnakrishnan2018', 'gsk215083', 'MNI152', '1mm'),
 ('raichle', 'cbf', 'fsLR', '164k'),
 ('raichle', 'cbv', 'fsLR', '164k'),
 ('raichle', 'cmr02', 'fsLR', '164k'),
 ('raichle', 'cmrglc', 'fsLR', '164k'),
 ('reardon2018', 'scalinghcp', 'civet', '41k'),
 ('reardon2018', 'scalingnih', 'civet', '41k'),
 ('reardon2018', 'scalingpnc', 'civet', '41k'),
 ('rosaneto', 'abp688', 'MNI152', '1mm'),
 ('sandiego2015', 'flb457', 'MNI152', '1mm'),
 ('sasaki2012', 'fepe2i', 'MNI152', '1mm'),
 ('satterthwaite2014', 'meancbf', 'MNI152', '1mm'),
 ('savli2012', 'altanserin', 'MNI152', '3mm'),
 ('savli2012', 'dasb', 'MNI152', '3mm'),
 ('savli2012', 'p943', 'MNI152', '3mm'),
 ('savli2012', 'way100635', 'MNI152', '3mm'),
 ('smart2019', 'abp688', 'MNI152', '1mm'),
 ('smith2017', 'flb457', 'MNI152', '1mm'),
 ('sydnor2021', 'SAaxis', 'fsLR', '32k'),
 ('tuominen', 'feobv', 'MNI152', '2mm'),
 ('turtonen2020', 'carfentanil', 'MNI152', '1mm'),
 ('vijay2018', 'ly2795050', 'MNI152', '2mm'),
 ('xu2020', 'FChomology', 'fsLR', '32k'),
 ('xu2020', 'evoexp', 'fsLR', '32k')]`

Running  fetch_annotation(source='galovic2021', desc='ge179', space='MNI152', res='1mm')
returns a blank
`{}`

Version 0.0.5 installed by using:
`git clone https://github.com/netneurolab/neuromaps
cd neuromaps
pip install .`

**Comment by Turius** [comment]
Sorry. I tried to reinstall by re-donwloading from git and now it works. I thought that using the same version, it would have fetched the dataset anyways.
