### ISSUE TITLE
Need help with loading maps from my own study

### ISSUE THREAD

**Issue by annchenruth** [netneurolab/neuromaps#36]
Hello,

I'm interested in using neuromaps to check the correspondence between some group-level maps I have in my study to the normative maps / annotations in the neuromaps database.   My maps are in fslr32k space, originally in cifti format, but i used `wb_command -cifti-convert` to convert to gii format, which enabled me to use the `load_gifti` function to successfully load a map into a nibabel gifti image object.  However, it seems it didn't quite work properly since `agg_data().shape` returns an error.  

Here is my code and output for my initial attempt to load and compare my map (POA) to the developmental expansion map in neuromaps (which appears to only be available for R hemi).

```
>>> POA_path = '/mnt/path/CT_POA_beta.shape.gii'
>>> POA = load_gifti(POA_path)
>>> POA
<nibabel.gifti.gifti.GiftiImage object at 0x7fd9f1ede7f0>
>>> POA.agg_data().shape
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'shape'
>>>
>>> devexp_path = fetch_annotation(source='hill2010', desc='devexp')
>>> devexp = load_gifti(devexp_path)
>>> devexp.agg_data().shape
(163842,)
>>>
>>> devexp_fslr32k, POA_fslr32k = resample_images(src=devexp_path, trg=POA_path,
...                                     src_space='fslr', trg_space='fslr',
...                                     method='linear', resampling='transform_to_alt',
...                                     hemi='R', alt_spec=('fslr', '32k'))

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rapiduser/.local/lib/python3.8/site-packages/neuromaps/resampling.py", line 271, in resample_images
    src, trg = func(src, trg, src_space, trg_space, hemi=hemi,
  File "/home/rapiduser/.local/lib/python3.8/site-packages/neuromaps/resampling.py", line 120, in transform_to_alt
    trg, _ = transform_to_trg(trg, alt_density, trg_space, alt_space,
  File "/home/rapiduser/.local/lib/python3.8/site-packages/neuromaps/resampling.py", line 95, in transform_to_trg
    src_den, trg_den = transforms._estimate_density((src, trg), hemi)
  File "/home/rapiduser/.local/lib/python3.8/site-packages/neuromaps/transforms.py", line 71, in _estimate_density
    n_vert = [len(load_data(d)) for d in img]
  File "/home/rapiduser/.local/lib/python3.8/site-packages/neuromaps/transforms.py", line 71, in <listcomp>
    n_vert = [len(load_data(d)) for d in img]
TypeError: len() of unsized object
>>>
```

Sorry if I'm missing something here - I'm fairly new to the cifti / gifti formats, and to neuromaps.  Any help would be appreciated, thanks!

**Comment by justinehansen** [comment]
Hey!

Try using `-cifti-separate` instead of `cifti-convert`, like this: `wb_command -cifti-separate $CIFTI_FILE COLUMN -metric CORTEX_LEFT lh_CT_POA_BETA.shape.gii -metric CORTEX_RIGHT rh_CT_POA_BETA.shape.gii` where `$CIFTI-FILE` is the path to your cifti file. That should give you the proper gifti file to load in using neuromaps.

Also yes you're right that the devexp map is only computed (and therefore availble) in the right hemisphere.

Hope that helps!

Justine

**Comment by annchenruth** [comment]
Ah, thanks for the quick response - that did the trick!!
