### ISSUE TITLE
[BUG] `inverse_transform()` function raises error about missing attribute

### ISSUE THREAD

**Issue by alyssadai** [netneurolab/neuromaps#59]
### Issue summary

When testing the `inverse_transform()` function of `neuromaps.parcellate.Parcellater` for projecting parcellated data back to the vertex level by continuing [this wiki example](https://netneurolab.github.io/neuromaps/user_guide/nulls.html#nulls-with-parcellated-data) (see Steps to reproduce), I encountered this error:

Error message:
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_399930/351554083.py in <module>
----> 1 abagen_parc_vtx = destrieux.inverse_transform(abagen_parc)

/gpfs/fs1/home/m/mchakrav/daialy/.virtualenvs/brainnot_venv/lib/python3.8/site-packages/neuromaps/parcellate.py in inverse_transform(self, data)
    171 
    172         if not self._volumetric:
--> 173             verts = parcels_to_vertices(data, self.parcellation, self.drop)
    174             img = _array_to_gifti(verts)
    175         else:

AttributeError: 'Parcellater' object has no attribute 'drop'
```

Could this be due to the following code passing an extra, third argument `self.drop` to `parcels_to_vertices()`?
https://github.com/netneurolab/neuromaps/blob/4257c0b7c4a25600abec487a5256a0f0aeb06280/neuromaps/parcellate.py#L172-L174

Whereas from what I can tell, the called function only accepts two args:
https://github.com/netneurolab/neuromaps/blob/8aaa841c3f3700e8d5fc6640bc53baebcf55d75b/neuromaps/nulls/spins.py#L513-L515

### Steps to reproduce issue

```python
from neuromaps import parcellate, datasets, images, nulls, resampling
from nilearn.datasets import fetch_atlas_surf_destrieux 

destrieux = fetch_atlas_surf_destrieux()
abagen = datasets.fetch_annotation(source='abagen') # func.gii

labels = [label.decode() for label in destrieux['labels']]
parc_left = images.construct_shape_gii(destrieux['map_left'], labels=labels,
                                       intent='NIFTI_INTENT_LABEL')
parc_right = images.construct_shape_gii(destrieux['map_right'], labels=labels,
                                        intent='NIFTI_INTENT_LABEL')
parcellation = images.relabel_gifti((parc_left, parc_right), background=['Medial_wall'])
destrieux = parcellate.Parcellater(parcellation, 'fsaverage').fit()

# parcellate data
abagen_parc = destrieux.transform(abagen, 'fsaverage')

# project data back to space + density of parcellation - this line raises the error
abagen_parc_vtx = destrieux.inverse_transform(abagen_parc)
```

### Software version

0.0.2

### What operating system were you using when you encountered this issue?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Code of Conduct

- [X] I agree to follow the `neuromaps` Code of Conduct

**Comment by VinceBaz** [comment]
Hey @alyssadai! The bug should now be fixed. Thank you so much for spotting it! Everything should be fine now so I'll close with issue.
