### ISSUE TITLE
How to circumvent internet access requirement?

### ISSUE THREAD

**Issue by Melissa1909** [netneurolab/neuromaps#69]
### Description of issue

Hey guys,

I am trying to use neuromaps.nulls.burt2020 inside a docker container on a Linux machine in my office since I have trouble running it on my own machine (get the error "no space left on device"...).
However, the computers in our office don't have internet access, which seems to be required to fetch data for the null map calculation. Is there an option to circumvent this problem?

Best, Melissa

### Code of Conduct

- [X] I agree to follow the `neuromaps` Code of Conduct

**Comment by VinceBaz** [comment]
Hey @Melissa1909! Yes, there should be a way to circumvent this problem. The null functionalities use brain atlases. When you first use the toolbox, they are downloaded from the Internet and stored in a `neuromaps-data` folder in your home directory. Once they are downloaded locally, you don't need internet access anymore. So what you could do if your machine does not have internet access is manually copy-paste this `neuromaps-data` folder into your home directory.

You can generate this folder on a machine that has internet access by calling the `neuromaps.datasets.fetch_all_atlases` function. This will automcatically create the `neuromaps-data` folder and download all the atlases that are available in neuromaps. You'll then need to somehow copy-paste this folder into the home directory of your other machine that does not have internet access (using a USB key or something?).

If you want, you could also use the `fetch_annotation(source='all')` to download all the annotations as well. They are not required to generate nulls, but they might still be useful to you in the future. 

Hopefully this should work, but let me know if it doesn't or if you have any other question! 😄 

Best,
Vincent

**Comment by Melissa1909** [comment]
That works, thank you! :)
