### ISSUE TITLE
Hill2010 maps missing left hemisphere [BUG] 

### ISSUE THREAD

**Issue by PeerHerholz** [netneurolab/neuromaps#76]
### Issue summary

The `Hill2010` maps only include the right hemisphere.

### Detailed issue description

When downloading the `Hill2010` maps, both the `evoexp` and `devexp` contain only the right hemisphere. After having a look at the respective `OSF` repo it seems that they are also missing there. Thus, I was wondering if the maps for the left hemisphere are not available or if this might be a bug?

Thanks for this great resource and your respective efforts!   

### Steps to reproduce issue

```python
>>> from neuromaps import datasets
>>> datasets.fetch_annotation(source='hill2010', desc='devexp')
>>> datasets.fetch_annotation(source='hill2010', desc='evoexp')
...
```

### Software version

0.0.3-rc.1+13.g54aebbb

### What operating system were you using when you encountered this issue?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Code of Conduct

- [X] I agree to follow the `neuromaps` Code of Conduct

**Comment by justinehansen** [comment]
Hi Peer,

Only the right hemispheres were available for both of these maps unfortunately 🙁 
We do have a newer evolutionary expansion map from [Xu et al., 2020](https://www.sciencedirect.com/science/article/pii/S1053811920308326) which includes both hemispheres. 

Sorry I couldn't be more helpful!

Justine

**Comment by PeerHerholz** [comment]
Hi @justinehansen,

all good, no problemo, and obviously not your fault. 
Yeah, I saw the maps from `Xu2020`, that's great, thx! 
Do you maybe have any hints regarding bilateral developmental expansion maps?

Thanks so much again. 

Best, Peer

**Comment by justinehansen** [comment]
Nothing immediately comes to mind but the [Sydnor 2021 S-A axis map](https://www.sciencedirect.com/science/article/pii/S0896627321004578#bib174) might be an alternative?
I also did a quick look at the papers they cite re: developmental expansion - I didn't find any cortical expansion type maps with available data but it might be worth doing a deeper look (for example [Raznahan 2011](https://www.jneurosci.org/content/31/19/7174.short) might be of interest?)

**Comment by PeerHerholz** [comment]
Hi @justinehansen,

thank you very much for the helpful reply and references, I highly appreciate it!

I would like to ask one question if it's ok (I can also move this to a different issue re traceability/not mixing threads). 
I was wondering if a future version of the `docs` might have some sort of "annotation glossary" entailing a short description of each map?

Best, Peer

**Comment by justinehansen** [comment]
Yes! We currently have a version of this [here](https://github.com/netneurolab/neuromaps/wiki/Annotation-information), and @liuzhenqi77 has been working on integrating this information into the fetchers themselves (see [PR#73](https://github.com/netneurolab/neuromaps/pull/73)). If you have suggestions for how to better integrate this information or if there is other info you'd like to see in the table, definitely let me know :slightly_smiling_face: 

Best,
Justine

**Comment by PeerHerholz** [comment]
Hi @justinehansen,

that's awesome, thx for sharing! Not sure how I missed this...sorry.
I thought about a `pandas df` or `dictionary` containing the information, so your solution works perfectly (at least for me but I would assume basically also for every other user).

Thanks so much again for all the helpful information and dedicated work on this, it's a fantastic resource.

Best, Peer

**Comment by PeerHerholz** [comment]
Hi @justinehansen,

I'm very sorry for the late reply. Oh, that looks super cool, thanks so much for the pointer! 
If you think it would also be useful for others, I'm happy to try adding it to `neuromaps`!?

**Comment by justinehansen** [comment]
Yeah that might be a good idea - let's put a hold on it for now (I'm going to try to better understand the data and how it could be used) but I'll follow up with you about this :grin:

**Comment by PeerHerholz** [comment]
Hi @justinehansen,

sure thing, hehe!
