### ISSUE TITLE
Issues when mapping PET data from MNI152 space to fsaverage

### ISSUE THREAD

**Issue by vbeliveau** [netneurolab/neuromaps#81]
### Description of issue

Dear netneurolab (@rmarkello, @justinehansen, @bmisic),

Thank you for your efforts in developing neuromaps!

While using your software for the first time, we have noticed some strange results regarding the data in the fsaverage (FreeSurfer surface) space.

Firstly, here is an example of the DASB map from Beliveau et al. 2017 that you re-distribute shown mapped onto the left faverage surface (inflated, lateral view):
 
![neuromaps_dasb](https://user-images.githubusercontent.com/7551274/202170525-c49c52c9-1fa8-4234-b158-efe03ca1f7cd.png)

And here is the same data that we originally published (see https://xtra.nru.dk/FS5ht-atlas/ for downloading the surface-based maps):
 
![NRU_dasb](https://user-images.githubusercontent.com/7551274/202170619-104ef71f-7623-4a43-8d6c-d2f9c58b902d.png)

Something seems to be wrong here. We suspect that the artefacts in the surface-based map obtained using neuromaps arise from not re-distributing the surface-based maps that we provide, but instead resampling the data from MNI152 space to the fsaverage surface. Although the cortical data is represented in the volumetric atlas (in MNI152 space) that we distribute (see https://xtra.nru.dk/FS5ht-atlas/ for downloading the volumetric maps as well), this was only ever done for visualization purposes. 

One of the main focus of our work (https://www.jneurosci.org/content/37/1/120) was to perform the modelling of positon emission tomography data properly – aka volumetrically when looking at volume data and on the surface when looking at surface data. 

Instead of resampling the data from MNI152 space to fsaverage, the cortical data already processed on the faverage surface should be directly provided to the user.

Could you please clarify if this process was employed in any of your recent publications besides the neuromaps article?

A second issue that we have noticed concerns the mapping from MNI152 space to fsaverage. Partial volume effects (PVE) are quite problematic with PET data. Smoothing PET data in the volume exacerbates partial volume effects. This was well described by Greve et al. 2014 (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4008670/) @dngreve and is one of the main motivators behind the development of PetSurfer. Nonetheless, smoothing of PET data in the volume is still part of most PET preprocessing workflows. 

However, when you map this volume-smoothed data to the surface, the PVE become strikingly apparent as stripe patterns which are closely related to the brain’s curvature. For this reason, PET volume-smoothed data is generally analyzed in the volume and not projected on the surface.

As an example, here is the volume-smoothed 5-HT1A maps from Savli et al. 2012 that you re-distribute mapped onto the fsaverage surface:
 
![neuromaps_way](https://user-images.githubusercontent.com/7551274/202170693-6be20547-ccb2-4ba4-acb0-6be1cf442abf.png)

And here is the equivalent surface-smoothed 5-HT1A map from Beliveau et al. 2017:

![NRU_cumi](https://user-images.githubusercontent.com/7551274/202170724-228fad16-fcec-4520-b22d-3551e62af0f1.png)

It seems to be clear that the 5HT1A maps from the Savli et al. data shows large PVEs.

In extreme cases, the PVEs can even override the underlying data. For example, here is the map of UCBJ from Finnema et al. 2016 that you distribute mapped onto the fsaverage surface:

![finnema2016](https://user-images.githubusercontent.com/7551274/202170761-49a1a8f1-bfc3-462f-b898-f9936c5b58dc.png)

And here is the curvature map of fsaverage, as a visual reference:
  
![curv](https://user-images.githubusercontent.com/7551274/202170785-5d008be0-6e81-46e4-a551-a8320d0025c8.png)

These large patterns of PVEs greatly limit the usefulness of these maps, and using them for quantification of biological associations is likely to be heavily biased.

We would greatly appreciate if you could comment on this issue and clarify if these maps were used as described here in your recent publications.

Vincent Beliveau (@vbeliveau) & Melanie Ganz (@melanieganz)

Below is an example script based on your repository (neuromaps=0.0.3) used to retrieve the maps presented above and transfer them to fsaverage:

```
import nibabel as nib

from neuromaps.datasets import fetch_annotation
from neuromaps import transforms

# DASB
annotation = fetch_annotation(source='beliveau2017', desc='dasb')

# Transform to fsaverage
beliveau2017_dasb  = transforms.mni152_to_fsaverage(annotation, '164k')

# Save out data
fsavg_lh, fsavg_rh = beliveau2017_dasb
nib.save(fsavg_lh, 'beliveau2017_PET-dasb_space-fsaverage-lh.gii')
nib.save(fsavg_rh, 'beliveau2017_PET-dasb_space-fsaverage-rh.gii')
```

### Code of Conduct

- [X] I agree to follow the `neuromaps` Code of Conduct

**Comment by justinehansen** [comment]
Hi @vbeliveau and @melanieganz,

It's great that you are testing neuromaps and thanks so much for your thorough description of the issue 🙂 

For all PET maps, we only provide the MNI152 volumetric map. Any fsaverage versions are created by the user, using `transforms.mni152_to_fsaverage`, which relies on a registration fusion framework. The original reason for this is that we only provide data in the space that they are originally presented (that is, we do not provide precomputed transformations) - however, I must've neglected (or forgotten) the fact that the 5-HT NRU data from Beliveau et al 2017 is also available in fsaverage space (which is awesome!). Since this is the case, I'm thinking the best way to move foward is to also include the fsaverage files. Do you think it's better if we remove the MNI152 version altogether?

I believe the fsaverage transformed brain surface you show of DASB from Beliveau 2017 is patchy (along with all volume-to-surface transformations of NRU PET data) because that volumetric data only exists as a grey matter ribbon, which isn't compatible with the `mni152_to_fsaverage()` function. We can definitely make this caveat clearer somewhere in the docs/wiki. Best case scenario is that we'd make the transformation function more generalizable, but since these data exist as fsaverage surfaces already, I completely agree it's best to upload the original fsaverage version instead of getting users to transform from MNI152 to fsaverage themselves. Of course feel free to let me know your thoughts/suggestions. 

Re PVE: it would be great if the `mni152_to_fsaverage` transformation function could be enhanced to better handle PET data. Right now I generally do not recommend transforming volume to surface for PET data, but if we could get the transformation function to a state where it better handles PET data, that would be amazing (and very useful I'm sure!). Do you have suggestions on this front? Do you think it would be possible to combine the registration fusion algorithm with previously existing software packages/methods for appropriately transforming PET volumes to the surface? Since the PET data are already organized in neuromaps with a "PET" tag, it should be easy to implement an `if` statement in the `mni152_to_[surface]()` functions for special handling of PET data.

One immediate way to go foward is just to make it clear that volume to surface transformations of PET data are not recommend, similar to how we recommend against surface to volume transformations in general.

Re recent work: in my case, I only use parcellated PET data, and I don't work at the surface level. Similarly, no one in the netneurolab is using vertex-level surface-transformed PET data. I can't speak for general neuromaps users, so it's definitely important to make it clear to users that applying volume to surface transformations on PET data requires extra attention. Hopefully we can improve these transformation functions to work well with volumetric PET data but you probably know better than I how to go about doing this 🙂 

Let me know what you think!

Thanks again for bringing this up,

Justine

**Comment by vbeliveau** [comment]
> Hi @vbeliveau and @melanieganz,
> 
> It's great that you are testing neuromaps and thanks so much for your thorough description of the issue 🙂
> 
> For all PET maps, we only provide the MNI152 volumetric map. Any fsaverage versions are created by the user, using `transforms.mni152_to_fsaverage`, which relies on a registration fusion framework. The original reason for this is that we only provide data in the space that they are originally presented (that is, we do not provide precomputed transformations) - however, I must've neglected (or forgotten) the fact that the 5-HT NRU data from Beliveau et al 2017 is also available in fsaverage space (which is awesome!). Since this is the case, I'm thinking the best way to move foward is to also include the fsaverage files. Do you think it's better if we remove the MNI152 version altogether?
> 
> I believe the fsaverage transformed brain surface you show of DASB from Beliveau 2017 is patchy (along with all volume-to-surface transformations of NRU PET data) because that volumetric data only exists as a grey matter ribbon, which isn't compatible with the `mni152_to_fsaverage()` function. We can definitely make this caveat clearer somewhere in the docs/wiki. Best case scenario is that we'd make the transformation function more generalizable, but since these data exist as fsaverage surfaces already, I completely agree it's best to upload the original fsaverage version instead of getting users to transform from MNI152 to fsaverage themselves. Of course feel free to let me know your thoughts/suggestions.
> 
> Re PVE: it would be great if the `mni152_to_fsaverage` transformation function could be enhanced to better handle PET data. Right now I generally do not recommend transforming volume to surface for PET data, but if we could get the transformation function to a state where it better handles PET data, that would be amazing (and very useful I'm sure!). Do you have suggestions on this front? Do you think it would be possible to combine the registration fusion algorithm with previously existing software packages/methods for appropriately transforming PET volumes to the surface? Since the PET data are already organized in neuromaps with a "PET" tag, it should be easy to implement an `if` statement in the `mni152_to_[surface]()` functions for special handling of PET data.
> 
> One immediate way to go foward is just to make it clear that volume to surface transformations of PET data are not recommend, similar to how we recommend against surface to volume transformations in general.
> 
> Re recent work: in my case, I only use parcellated PET data, and I don't work at the surface level. Similarly, no one in the netneurolab is using vertex-level surface-transformed PET data. I can't speak for general neuromaps users, so it's definitely important to make it clear to users that applying volume to surface transformations on PET data requires extra attention. Hopefully we can improve these transformation functions to work well with volumetric PET data but you probably know better than I how to go about doing this 🙂
> 
> Let me know what you think!
> 
> Thanks again for bringing this up,
> 
> Justine

**Comment by vbeliveau** [comment]
Hi @justinehansen, thanks for the quick reply :)

Also, apologies for accidentally closing the issue.

> For all PET maps, we only provide the MNI152 volumetric map. Any fsaverage versions are created by the user, using `transforms.mni152_to_fsaverage`, which relies on a registration fusion framework. The original reason for this is that we only provide data in the space that they are originally presented (that is, we do not provide precomputed transformations) - however, I must've neglected (or forgotten) the fact that the 5-HT NRU data from Beliveau et al 2017 is also available in fsaverage space (which is awesome!). Since this is the case, I'm thinking the best way to move foward is to also include the fsaverage files. Do you think it's better if we remove the MNI152 version altogether?
> 

Our maps in MNI152 space can be included, but when the user requests the data in the fsaverage space, the native fsaverage maps that we distribute should be provided, rather than resampling the data from MNI152 space.

> I believe the fsaverage transformed brain surface you show of DASB from Beliveau 2017 is patchy (along with all volume-to-surface transformations of NRU PET data) because that volumetric data only exists as a grey matter ribbon, which isn't compatible with the `mni152_to_fsaverage()` function. We can definitely make this caveat clearer somewhere in the docs/wiki. Best case scenario is that we'd make the transformation function more generalizable, but since these data exist as fsaverage surfaces already, I completely agree it's best to upload the original fsaverage version instead of getting users to transform from MNI152 to fsaverage themselves. Of course feel free to let me know your thoughts/suggestions.
> 

Same as above.

> Re PVE: it would be great if the `mni152_to_fsaverage` transformation function could be enhanced to better handle PET data. Right now I generally do not recommend transforming volume to surface for PET data, but if we could get the transformation function to a state where it better handles PET data, that would be amazing (and very useful I'm sure!). Do you have suggestions on this front? Do you think it would be possible to combine the registration fusion algorithm with previously existing software packages/methods for appropriately transforming PET volumes to the surface? Since the PET data are already organized in neuromaps with a "PET" tag, it should be easy to implement an `if` statement in the `mni152_to_[surface]()` functions for special handling of PET data.
> 
> One immediate way to go foward is just to make it clear that volume to surface transformations of PET data are not recommend, similar to how we recommend against surface to volume transformations in general.
>

I am of the opinion that volume-smoothed PET data should simply not be used on the surface. The underlying data is essentially corrupted by PVEs, and there is no spatial transformation that will be able to account for that. My recommendation would be to add a very large warning to the users when they requests PET data that was volume-smoothed to be resampled from MNI152 to the surface.
 
> Re recent work: in my case, I only use parcellated PET data, and I don't work at the surface level. Similarly, no one in the netneurolab is using vertex-level surface-transformed PET data. I can't speak for general neuromaps users, so it's definitely important to make it clear to users that applying volume to surface transformations on PET data requires extra attention. Hopefully we can improve these transformation functions to work well with volumetric PET data but you probably know better than I how to go about doing this 🙂
> 

I am not sure I follow your "I don't work at the surface level". Didn't you use the Desikan-Killiany and the Schaeffer atlases, which are surface-based atlases, to parcellate the PET data in some of your papers (https://www.nature.com/articles/s41467-022-32420-y, https://www.nature.com/articles/s41593-022-01186-3)? If so, then that statement wouldn't be entirely correct. When looking at some of your code for one of the papers above (https://github.com/justinehansen/hansen_receptors-1/blob/main/code/parcellate.py) it does worryingly seem like you are mapping data PET (including ours) from MNI152 space to the surface space where the atlases are defined in order to "parcellate" that data. Or are you saying that you somehow parcellated the PET data without ever resampling it onto the surface? Sorry for poking at this, but given the issues raised above, I think that it is relevant to get to the bottom of this.

**Comment by justinehansen** [comment]
Hi Vincent,

I will add the fsaverage versions of the serotonin atlas to neuromaps. Do you happen to know if a similar fsaverage version exists for the GABAa map from Norgaard et al 2021? I'm also happy to add a warning about volume to surface transforms of PET data. I agree it's important for users to know about this!

In my own work, I parcellate data using parcellations that exist at the volumetric space. In other words, I take BP values (or Vmax etc) directly from the volume, and average non-background voxels that map onto a specific atlas-defined parcel. I don't transform voxel-level volumes to vertex-level surfaces before parcellating. So I guess after parcellating the volumes, the data exists on the surface, but this is on the order of 100 brain regions, not thousands of vertices. By "I don't work at the surface leve", I simply meant I don't work with vertex-level PET receptor data. Sorry I was unclear in my first comment.

The Schaefer parcellation in volumetric format is being fetched from [here](https://nilearn.github.io/dev/modules/generated/nilearn.datasets.fetch_atlas_schaefer_2018.html), and the DK atlas (actually the Cammoun-033 atlas which is equivalent to DK but ordered differently) is being fetched from [here](https://github.com/netneurolab/netneurotools/blob/master/netneurotools/datasets/fetchers.py#L22).

Let me know if there is anything else I can clarify,

Justine

**Comment by vbeliveau** [comment]
Hi again @justinehansen,

> I will add the fsaverage versions of the serotonin atlas to neuromaps. Do you happen to know if a similar fsaverage version exists for the GABAa map from Norgaard et al 2021? I'm also happy to add a warning about volume to surface transforms of PET data. I agree it's important for users to know about this!
> 

The main website for the BZR maps from @mnoergaard is: https://xtra.nru.dk/BZR-atlas/. The maps, including data on fsaverage, can be downloaded from here: https://xtra.nru.dk/BZR-atlas/data/BZR_atlas.zip.

> In my own work, I parcellate data using parcellations that exist at the volumetric space. In other words, I take BP values (or Vmax etc) directly from the volume, and average non-background voxels that map onto a specific atlas-defined parcel. I don't transform voxel-level volumes to vertex-level surfaces before parcellating. So I guess after parcellating the volumes, the data exists on the surface, but this is on the order of 100 brain regions, not thousands of vertices. By "I don't work at the surface leve", I simply meant I don't work with vertex-level PET receptor data. Sorry I was unclear in my first comment.
> 

It's very good to hear that you did not resample the data from MNI152 space to the surface and, therefore, do not suffer from the issues above (especially the one concerning our data). Given that these atlases are defined natively on the surface (at least the DK atlas), I must say that I was a bit surprised by this. It is not immediately apparent from the papers that you are using a volumetric version of the parcellations (and is perhaps worth emphasizing in the future). For example, for the DK parcellation, you write:

https://www.nature.com/articles/s41467-022-32420-y
> Volumetric PET images were registered to the MNI-ICBM 152 nonlinear 2009 (version c, asymmetric) template, averaged across participants within each study, then parcellated to 68 cortical regions.
>

For me, a further source of confusion came from the fact that you use the parcellated data on the surface when performing permutation testing. This volume-to-surface mapping of the parcellated data that you describe is not something I have previously seen and one would generally assume that the data was instead mapped onto the surface where the parcellation is defined.

Maybe as a final note: Although it does make sense with the other PET maps in MNI152 space, using a volumetric parcellation with our MNI152 maps is definitely suboptimal if a surface-based version of the parcellation exists given that our data is available on fsaverage. I would strongly suggest to include some kind of warning to the users about our maps in MNI152 space, either in the documentation or printed out when they load the maps, saying that these maps 1) should only be used to look at subcortical regions, 2) should not be resampled to fsaverage, and 3) should not be used in combination with a volume-based parcellation, if possible, but rather use a surface-based parcellation with the fsaverage maps.

**Comment by justinehansen** [comment]
Hi @vbeliveau,

This all sounds good to me! I'll update neuromaps with the fsaverage surfaces and warnings for volume-to-surface PET transforms as well as more specifically that the NRU data is best used and parcellated from the surface. Thanks for taking the time to explain this issue 🙂 (Please leave the issue open for now)

Best,
Justine
