### ISSUE TITLE
Issues when comparing maps with nulls.alexander_bloch()

### ISSUE THREAD

**Issue by enicolaisen** [netneurolab/neuromaps#82]
### Description of issue

Dear netneurolab,

thanks for developing neuromaps! It is a great tool! :)

I am having an issue when comparing `abagen` with `margulies2016` (`fcgradient01`). When running the code below several times, I get different correlations (which seems to always fluctuate between two values). 

Thanks for your help!

Best,
Eliana Nicolaisen

```
# Import libraries
from neuromaps import datasets
from neuromaps import transforms
from neuromaps import images, nulls
from neuromaps import stats
from neuromaps import parcellate

# Get metadata of margulies first gradient
marg01_annot = datasets.available_annotations(source='margulies2016',desc='fcgradient01')
abagen_annot = datasets.available_annotations(source='abagen')

#Fetch neuromaps
marg01      = datasets.fetch_annotation(source='margulies2016', desc='fcgradient01')
abagen      = datasets.fetch_annotation(source='abagen')

#transform FC gradient to fsaverage
marg01_fsaverage = transforms.fslr_to_fsaverage(marg01, target_density='10k', hemi={'L', 'R'}, method='linear')

# Rotate FC gradient
rotated = nulls.alexander_bloch(marg01_fsaverage, atlas='fsaverage', density='10k',n_perm=100, seed=20,parcellation=None)

#IMPORTANT:
# #The null array provided to the nulls argument in the stats.compare_images must be for the data passed as the first positional argument of the function! 
corr, pval = stats.compare_images(marg01_fsaverage,abagen, nulls=rotated)
print(f'Correlation: r = {corr:.02f}, p = {pval:.04f}')
```

### Code of Conduct

- [X] I agree to follow the `neuromaps` Code of Conduct

**Comment by enicolaisen** [comment]
Hi Justine,

thank you very much for your help and tips :)

Indeed, when setting `hemi=None` in the `transforms.fslr_to_fsaverage` I get consistent correlations. Just for completeness, I got the fluctuating correlations after running the code 5-7 times, and the fluctuation always happened between two values: `-0.52, p = 0.0099` and `-0.25, p = 0.2178`.

Thanks for your help on solving this issue!

Best,
Eli

**Comment by justinehansen** [comment]
Awesome, I'm glad it worked out 😄 

J
