### ISSUE TITLE
resample_images not checking for when source and target spaces are both 'MNI152'

### ISSUE THREAD

**Issue by VictorBarnes** [netneurolab/neuromaps#89]
### Description of issue

Line 257 of resampling.py (in the resample_images function) looks like this:
`elif src_space == 'MNI152' and src_space == 'MNI152':`
which is just checking the same thing twice. Shouldn't it be checking if both the source and **target** spaces are 'MNI152'? i.e.
`elif src_space == 'MNI152' and trg_space == 'MNI152':`

### Code of Conduct

- [X] I agree to follow the `neuromaps` Code of Conduct

**Comment by justinehansen** [comment]
I postponed this for 9 months and in the end it took me maybe 30 seconds to implement.

thanks for pointing out this bug!

J
