### ISSUE TITLE
Error when using any map from the annotations that uses fsLR 4k density

### ISSUE THREAD

**Issue by Ghadiirr** [netneurolab/neuromaps#96]
### Description of issue

I'm trying to compare maps from my lab with MEG power distribution maps from the Human Connectome Project S1200 release, these maps uses the fsLR atlas with 4k density. The problem is I cannot plot, resample, perform any statistical analysis as the function to fetch the fsLR atlas 4k is returning with an error saying the source is empty. I tried to obtain the atlas from other sources but couldn't fine anything with similar density.
Is there anyway to get the atlas from you?

### Code of Conduct

- [X] I agree to follow the `neuromaps` Code of Conduct

**Comment by justinehansen** [comment]
Thanks for reaching out! We had a recent pull request (PR #92) that fiddled with some fslr4k maps, is it possible you are using an older version of neuromaps? Try updating neuromaps to the most recent version on github (not yet on pip) and let me know if you still get the same issue. If that doesn't work, could you send me the precise line of code and the error message that you get?

Best,
Justine

**Comment by Ghadiirr** [comment]
you're right! it seems to work fine after the update! thanks for the help
