### ISSUE TITLE
error fetching hcps1200-thickness files

### ISSUE THREAD

**Issue by sgtyshu** [netneurolab/neuromaps#99]
### Description of issue

When I am using code like:
`datasets.fetch_annotation(source = 'hcps1200',desc = 'thickness', hemi = 'R')`
and
`datasets.fetch_annotation(source = 'hcps1200',desc = 'thickness', hemi = 'L')`
It seems I have downloaded the same file, and both are 'source-hcps1200_desc-thickness_space-fsLR_den-32k_hemi-R_feature.func.gii'.
Is there any documentation about this issue?
### Code of Conduct

- [X] I agree to follow the `neuromaps` Code of Conduct

**Comment by justinehansen** [comment]
Hi @sgtyshu! I can't seem to replicate your error, maybe try updating neuormaps to the most current version on github? eg `pip install git+https://github.com/netneurolab/neuromaps`. Let me know if that fixes things for you.

**Comment by VinceBaz** [comment]
Hi @sgtyshu, this is indeed a bug! Thank you so much for noticing it! This error somehow crept in in [PR#20](https://github.com/netneurolab/neuromaps/pull/20). We'll fix this ASAP

**Comment by VinceBaz** [comment]
Hi Again @sgtyshu. The bug should now be fixed, so I'll close this, but let us know if you run into other issues.

Best,
Vince
